prostage_accueil:
    path: /accueil
    controller: App\Controller\ProstageController::index

prostage_bvn:
    path: /
    controller: App\Controller\ProstageController::bvn

prostage_entreprises:
    path: /entreprises
    controller: App\Controller\ProstageController::entreprises

prostage_ajouterEntreprise:
    path: /entreprises/ajouter
    controller: App\Controller\ProstageController::ajouterEntreprise

prostage_formations:
    path: /formations
    controller: App\Controller\ProstageController::formations

prostage_stages:
    path: /stages/{id}
    controller: App\Controller\ProstageController::stages

prostage_parEntreprise:
    path: /parentreprise/{id}
    controller: App\Controller\ProstageController::parEntreprise

prostage_parFormation:
    path: /parformation/{id}
    controller: App\Controller\ProstageController::parFormation

prostage_aPropos:
    path: /apropos
    controller: App\Controller\ProstageController::aPropos